apiVersion: v1
kind: Service
metadata:
  labels:
    app: flaskapp32
  name: flaskapp32
spec:
  type: NodePort
  ports:
    - port: 5070
      targetPort: 5070
      protocol: TCP
  selector:
    app: flaskapp32
