apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp_32
  labels:
    app: flaskapp_32
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp_32
  template:
    metadata:
      labels:
        app: flaskapp_32
    spec:
      containers:
      - name: flaskapp_32
        image: thejasbp/flaskappexam:v1
        ports:
        - containerPort: 5070
